In [ ]:
from google.colab import files
uploaded = files.upload()

MessageError: ignored

In [ ]:
!pip install nlppreprocess
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
%matplotlib inline
import string
import re
import nltk
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer 
from wordcloud import WordCloud
import string
from nlppreprocess import NLP
import pickle
# splitting data
from sklearn.model_selection import train_test_split
# Features Extraction
from sklearn.feature_extraction.text import CountVectorizer
# Features Extraction
from sklearn.feature_extraction.text import TfidfVectorizer

# Evaluation
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score

# models
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
# from sklearn.svm import SVC

from sklearn import preprocessing

from sklearn.svm import SVC

# # Features Extraction word2vec
# from gensim.models import Word2Vec

# # Dimension reduction
# from sklearn.decomposition import PCA

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [ ]:
import io
df_file = pd.read_csv(io.BytesIO(uploaded['cleaned_arabic_tweets.csv']))
df_file.dropna(inplace=True)
print(len(df_file))
df_file.head()

5991


tweet  class
0                           فينو الاهبل ابن الاهبل        0
1    علي المصرييييين وجمالهم ربنا يحميهم  MinaAtta        1
2  دول كتير اوي ودمهم خفيف العماره اللي انا كلها ...      1
3  انا بعد كده خلي اللي يوعني بحاجه همضي علي وصل ...      0
4                                        انا هنتحر        0

In [ ]:
df_file = df_file.sample(frac=1).reset_index(drop=True) # shuffel
print(len(df_file))
df_file.head()

5991


tweet  class
0  لا لازدواجيه المعايير عند نبذ العنف  لا لتبرير...      0
1   الوطن زعزوع   مصر اتخذت اجراءات جديده لتسهيل ...      2
2                      معلش بقي مجتمع معاااااااااق        0
3                        بقينا اتنين غراب عن بعض          0
4                                        عته والله        0

In [ ]:
text_list = list(df_file['tweet'])
print(len(text_list))
X = text_list
y = df_file['class']


5991


In [ ]:
def count_vectorize(df):
    '''
    Argumen:
        df dataframe of multiple reviews
    return:
        Train & test arrays that can fir to the model
    '''
# I fit the vector to all of the data
    vectorizer = CountVectorizer()
    vectorize = vectorizer.fit(df) 
    return vectorizer

In [ ]:
count_vectorizer = count_vectorize(X)
pickle.dump(count_vectorizer, open("arabic_count_vectorizer_5991.pickle", "wb"))
files.download('arabic_count_vectorizer_5991.pickle')
count_vectorizer = pickle.load(open("arabic_count_vectorizer_5991.pickle", "rb"))

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.2)
print("Our training data now are: " + str(len(X_train))  + " tweet")
print("Our testing data now are: " + str(len(X_test))  + " tweet")
print("Our training data now are: " + str(len(y_train))  + " labels")
print("Our testing data now are: " + str(len(y_test))  + " labels")

Our training data now are: 4792 tweet
Our testing data now are: 1199 tweet
Our training data now are: 4792 labels
Our testing data now are: 1199 labels


In [ ]:

training_data = count_vectorizer.transform(X_train)
training_data  = training_data.toarray()
testing_data = count_vectorizer.transform(X_test)
testing_data  = testing_data.toarray()

In [ ]:
clf_MultinomialNB = MultinomialNB()
model = clf_MultinomialNB.fit(training_data, y_train)
predict = model.predict(training_data)
print("F1 score of our training data is: ", f1_score(y_train, predict, average='micro'))
print("Evalution Matrix of training data is \n", confusion_matrix(y_train, predict))
predict = model.predict(testing_data)
print("F1 score of our testing data is: ", f1_score(y_test, predict, average='micro'))
print("Evalution Matrix of training data is \n", confusion_matrix(y_test, predict))

F1 score of our training data is:  0.9403171953255426
Evalution Matrix of training data is 
 [[2027   35    6]
 [  73 1375    9]
 [ 120   43 1104]]
F1 score of our testing data is:  0.5396163469557965
Evalution Matrix of training data is 
 [[352  75  92]
 [ 96 221  43]
 [168  78  74]]


In [ ]:
# pickle.dump(model, open("MultinomialNB_Arabic_54%_5991.pickle", "wb"))
# files.download('MultinomialNB_63%_25000.pickle')
# count_vectorizer = pickle.load(open("MultinomialNB_Arabic_54%_5991.pickle", "rb"))

In [ ]:
clf_LogisticRegression = LogisticRegression(penalty='l2', solver='liblinear')
logistic_model = clf_LogisticRegression.fit(training_data, y_train)
predict = logistic_model.predict(training_data)
print("F1 score of our testing data is: ", f1_score(y_train, predict, average='micro'))
print("Evalution Matrix of training data is \n", confusion_matrix(y_train, predict))
predict = logistic_model.predict(testing_data)
print("F1 score of our testing data is: ", f1_score(y_test, predict, average='micro'))
print("Evalution Matrix of training data is \n", confusion_matrix(y_test, predict))

F1 score of our testing data is:  0.9837228714524207
Evalution Matrix of training data is 
 [[2049   17    2]
 [  11 1444    2]
 [  28   18 1221]]
F1 score of our testing data is:  0.5537948290241869
Evalution Matrix of training data is 
 [[378  68  73]
 [100 222  38]
 [178  78  64]]
